---
- name: Destroy VM instances
  hosts: 127.0.0.1
  connection: local
  gather_facts: no

  tasks:
    - name: Power down and destroy RHEL 8 VM instance 
      community.vmware.vmware_guest:
        validate_certs: no
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        name: "{{ rhel_8_vm_name }}"
        delete_from_inventory: yes
        state: absent
        force: yes

    - name: Power down and destroy CentOS Stream VM instance 
      community.vmware.vmware_guest:
        validate_certs: no
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        name: "{{ centos_stream_vm_name }}"
        delete_from_inventory: yes
        state: absent
        force: yes

    - name: Power down and destroy Oracle 8 VM instance 
      community.vmware.vmware_guest:
        validate_certs: no
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        name: "{{ oracle_8_vm_name }}"
        delete_from_inventory: yes
        state: absent
        force: yes

